In [1]:
import numpy as np

1.15.4


In [5]:
np.zeros(10, dtype='int16')
np.zeros(10, dtype=np.bool_)

array([False, False, False, False, False, False, False, False, False,
       False])

In [17]:
# Attribute of arrays
np.random.seed(1)
x1 = np.random.randint(10, size=3)
x2 = np.random.randint(10, size=(2, 3))
x3 = np.random.randint(10, size=(2, 3, 4))

print(x1.ndim, x2.ndim, x3.ndim)
print(x1.shape, x2.shape, x3.shape)
print(x1.size, x2.size, x3.size)
print(x1.dtype)

1 2 3
(3,) (2, 3) (2, 3, 4)
3 6 24
int64
[[5 0 0]
 [1 7 6]]
[[ 5 93 -9]
 [ 1  7  6]]


In [18]:
# Indexing of arrays
print(x2)
x2[0, 1] = 93
x2[0][2] = -9.33 # since array type is fixed, -9.33 will be truncated to -9
print(x2)


[[ 5 93 -9]
 [ 1  7  6]]
[[ 5 93 -9]
 [ 1  7  6]]


In [30]:
# Slicing of arrays x[start:stop:step], default for start=0, stop=size, step=1
arr = [1,2,3,4,5,6,7,8]
print(arr[::2])  # every other element
print(arr[1::2]) # every other element starting at index 1
print(arr[::-1]) # Reverse
print('--------------')
print(x2)
x2_sub = x2[0:2, 0:2]
print(x2_sub)
x2_sub[0, 1] = 1  # change at x2_sub will also affect on x2_sub due to reference inference
print(x2)
x2_copy = x2[0:2, 0:2].copy() # use copy() is the way to prevent object being modified

[1, 3, 5, 7]
[2, 4, 6, 8]
[8, 7, 6, 5, 4, 3, 2, 1]
--------------
[[ 5  1 -9]
 [ 1  7  6]]
[[5 1]
 [1 7]]
[[ 5  1 -9]
 [ 1  7  6]]


In [36]:
# Reshaping of arrays
arr = np.array(range(1,10))
grid2d = arr.reshape(3,3) # default use no copy
print(grid2d)
grid3d = np.arange(1, 9).reshape(2,2,2)
print(grid3d)

[[ 1  2  3]
 [-4  5  6]
 [ 7  8  9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Concatenation & splitting
# np.concatenate, np.vstack, np.hstack
a = np.array([1,2,3])
b = np.array([4,5,6])
d = np.array([7,7,7])
c = np.concatenate([a,b, d])
print(c)

grid = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([grid, grid], axis = 0))
print(np.concatenate([grid, grid], axis = 1))


[1 2 3 4 5 6 7 7 7]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [44]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

big_array = np.random.randint(1,100, size=100000)
# each time python needs to check the object type that slows down entire process
%timeit compute_reciprocals(big_array)


1 loop, best of 3: 425 ms per loop


In [43]:
%timeit 1.0/big_array

1000 loops, best of 3: 315 µs per loop
